#ifndef ROS_M_H
#define ROS_M_H



#define PKG_NAME "spear_mint"

#define ROS_MASTER_IP		"10.0.0.1"
#define ROS_MASTER_PORT		11311

#define ROS_HOST_IP		"10.0.0.2"
#define ROS_HOST_XMLRPC_PORT	2004
#define ROS_HOST_TCPROS_PORT	2005

#define XMLRPC_BUFFER_MAX_SIZE		1024
#define TCPROS_INIT_BUFFER_MAX_SIZE	1024
#define TCPROS_BUFFER_MAX_SIZE		128

#define XMLRPC_SERVER_TASK_STACK_SIZE 600
#define TCPROS_SERVER_TASK_STACK_SIZE 600
#define TOPIC_RECV_CONNECTION_TASK_STACK_SIZE 500
#define TOPIC_SEND_SERVICE_SERVER_CONNECTION_TASK_STACK_SIZE 500


#define ROS_M_SERVER_XMLRPC_TASK_PRIORITY 7
#define ROS_M_SERVER_TCPROS_TASK_PRIORITY 7
#define ROS_M_CONNECTION_TOPIC_RECV_TASK_PRIORITY 7
#define ROS_M_CONNECTION_TOPIC_SEND_SERVICE_SERVER_TASK_PRIORITY 7


#endif
