#ifndef ROS_M_H
#define ROS_M_H



#define PKG_NAME "ros_m"

#define ROS_MASTER_IP "192.168.20.4"
#define ROS_MASTER_PORT 11311

#define ROS_HOST_IP "192.168.20.4"
#define ROS_HOST_XMLRPC_PORT 2000
#define ROS_HOST_TCPROS_PORT 2001


#define ROS_M_SERVER_XMLRPC_TASK_PRIORITY 0
#define ROS_M_SERVER_TCPROS_TASK_PRIORITY 0
#define ROS_M_CONNECTION_TOPIC_RECV_TASK_PRIORITY 0
#define ROS_M_CONNECTION_TOPIC_SEND_SERVICE_SERVER_TASK_PRIORITY 0


#endif
